# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 极客算法DEBUG
brief-intro: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1:4000/" # the base hostname & protocol for your site
static: "http://127.0.0.1:4000/"

permalink: /:categories/:title


# other links
twitter_username:
facebook_username:
github_username:  geemaple
email: geemaple@gmail.com
weibo_username:
zhihu_username:
linkedIn_username:
dribbble_username:

description_footer: 极客算法DEBUG

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
duoshuo_shortname: #hygblog
disqus_shortname: geemaple

google_analytics_id: UA-118279055-1 # google 分析追踪id
google_tag_id: # G-5PKFSPN668

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

category_dir: category/
tag_dir: tag/

# plugins
plugins:
 - jekyll-paginate
 - jekyll-sitemap
 - jekyll-seo-tag
 - jekyll-debug

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
paginate: 6